// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: player_information.proto

package cache_handler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListString        string   `protobuf:"bytes,1,opt,name=listString,proto3" json:"listString,omitempty"`
	PlaybackTime      string   `protobuf:"bytes,2,opt,name=playbackTime,proto3" json:"playbackTime,omitempty"`
	Duration          string   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	PercentProgresBar int32    `protobuf:"varint,4,opt,name=percentProgresBar,proto3" json:"percentProgresBar,omitempty"`
	Volume            int32    `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Paused            bool     `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"`
	Playing           bool     `protobuf:"varint,7,opt,name=playing,proto3" json:"playing,omitempty"`
	SearchTxt         string   `protobuf:"bytes,8,opt,name=searchTxt,proto3" json:"searchTxt,omitempty"`
	Muted             bool     `protobuf:"varint,9,opt,name=muted,proto3" json:"muted,omitempty"`
	SearchResults     []string `protobuf:"bytes,10,rep,name=searchResults,proto3" json:"searchResults,omitempty"`
}

func (x *PlayerInformation) Reset() {
	*x = PlayerInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_information_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInformation) ProtoMessage() {}

func (x *PlayerInformation) ProtoReflect() protoreflect.Message {
	mi := &file_player_information_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInformation.ProtoReflect.Descriptor instead.
func (*PlayerInformation) Descriptor() ([]byte, []int) {
	return file_player_information_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInformation) GetListString() string {
	if x != nil {
		return x.ListString
	}
	return ""
}

func (x *PlayerInformation) GetPlaybackTime() string {
	if x != nil {
		return x.PlaybackTime
	}
	return ""
}

func (x *PlayerInformation) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *PlayerInformation) GetPercentProgresBar() int32 {
	if x != nil {
		return x.PercentProgresBar
	}
	return 0
}

func (x *PlayerInformation) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PlayerInformation) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *PlayerInformation) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *PlayerInformation) GetSearchTxt() string {
	if x != nil {
		return x.SearchTxt
	}
	return ""
}

func (x *PlayerInformation) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *PlayerInformation) GetSearchResults() []string {
	if x != nil {
		return x.SearchResults
	}
	return nil
}

var File_player_information_proto protoreflect.FileDescriptor

var file_player_information_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x22, 0xc5, 0x02, 0x0a, 0x11, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2c, 0x0a, 0x11, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x42, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x42, 0x61, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x54, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x54, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_player_information_proto_rawDescOnce sync.Once
	file_player_information_proto_rawDescData = file_player_information_proto_rawDesc
)

func file_player_information_proto_rawDescGZIP() []byte {
	file_player_information_proto_rawDescOnce.Do(func() {
		file_player_information_proto_rawDescData = protoimpl.X.CompressGZIP(file_player_information_proto_rawDescData)
	})
	return file_player_information_proto_rawDescData
}

var file_player_information_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_player_information_proto_goTypes = []interface{}{
	(*PlayerInformation)(nil), // 0: cache_handler.PlayerInformation
}
var file_player_information_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_information_proto_init() }
func file_player_information_proto_init() {
	if File_player_information_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_player_information_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_player_information_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_information_proto_goTypes,
		DependencyIndexes: file_player_information_proto_depIdxs,
		MessageInfos:      file_player_information_proto_msgTypes,
	}.Build()
	File_player_information_proto = out.File
	file_player_information_proto_rawDesc = nil
	file_player_information_proto_goTypes = nil
	file_player_information_proto_depIdxs = nil
}
